%YAML:1.0

File.version: "1.0"

#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

Camera1.fx: 382.613
Camera1.fy: 382.613
Camera1.cx: 320.183
Camera1.cy: 236.455

Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0

Camera.width: 640
Camera.height: 480

Camera.fps: 30

Camera.RGB: 1

#--------------------------------------------------------------------------------------------
# LiDAR Parameters
#--------------------------------------------------------------------------------------------
LiDAR.Tr11: 4.276802385584e-04
LiDAR.Tr12: -9.999672484946e-01
LiDAR.Tr13: -8.084491683471e-03
LiDAR.Tr14: -1.198459927713e-02
LiDAR.Tr21: -7.210626507497e-03
LiDAR.Tr22: 8.081198471645e-03
LiDAR.Tr23: -9.999413164504e-01
LiDAR.Tr24: -5.403984729748e-02
LiDAR.Tr31: 9.999738645903e-01
LiDAR.Tr32: 4.859485810390e-04
LiDAR.Tr33: -7.206933692422e-03
LiDAR.Tr34: -2.921968648686e-01

#LiDAR.Method: "NearestNeighborPixel"
#LiDAR.Method: "AverageFiltering"
LiDAR.Method: "InverseDilation"

LiDAR.min_dist: 5.0
LiDAR.max_dist: 200.0

LiDAR.MethodNearestNeighborPixel.SearchDistance: 7.0

# For Average Filtering
LiDAR.MethodAverageFiltering.bDoDilationPreprocessing: 1
LiDAR.MethodAverageFiltering.DilationPreprocessing_KernelType: "Diamond"
LiDAR.MethodAverageFiltering.DilationPreprocessing_KernelSize: 3.0
LiDAR.MethodAverageFiltering.KernelSize: 5.0

# For Inverse Dilation
LiDAR.MethodInverseDilation.KernelType: "Diamond"
LiDAR.MethodInverseDilation.KernelSize_u: 5.0 # width of the kernel
LiDAR.MethodInverseDilation.KernelSize_v: 7.0 # height of the kernel; not considered in Diamond mode

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1250

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.6
Viewer.KeyFrameLineWidth: 2.0
Viewer.GraphLineWidth: 1.0
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.7
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -100.0
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000.0
