%YAML:1.0

System.SaveAtlasToFile: "slam_session"

#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Left Camera (infra1)
Camera1.fx: 418.7626037597656
Camera1.fy: 418.7626037597656
Camera1.cx: 426.1114807128906
Camera1.cy: 237.3102569580078

# Distortion (plumb_bob = radial+tangential) — your data is undistorted
Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0
Camera1.k3: 0.0

# Right Camera (infra2)
Camera2.fx: 418.7626037597656
Camera2.fy: 418.7626037597656
Camera2.cx: 426.1114807128906
Camera2.cy: 237.3102569580078

Camera2.k1: 0.0
Camera2.k2: 0.0
Camera2.p1: 0.0
Camera2.p2: 0.0
Camera2.k3: 0.0

# Transformation from right (Camera2) to left (Camera1)
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [1.0, 0.0, 0.0, 0.0499898493289948,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 1.0, 0.0,
         0.0, 0.0, 0.0, 1.0]

# Image resolution
Camera.width: 848
Camera.height: 480

# Frame rate
Camera.fps: 30

# Color image? (0: BGR, 1: RGB) — ignored for grayscale
Camera.RGB: 0

# Threshold for close/far stereo points (in meters)
Stereo.ThDepth: 40.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

ORBextractor.nFeatures: 1000
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 15
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------

Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0